name: release

on:
  push:
    branches: [main]

permissions:
  contents: write
  pull-requests: write

jobs:
  metadata:
    runs-on: ubuntu-latest
    outputs:
      release-created: ${{ steps.metadata.outputs.release_created }}
    steps:
      - name: Update project metadata and release pull request
        id: metadata
        uses: googleapis/release-please-action@v4
        with:
          release-type: simple
  deploy:
    needs: [metadata]
    if: ${{ needs.metadata.outputs.release-created}}
    uses: ./.github/workflows/deploy.yaml
